name: Setup macOS, Install Dependencies, Run PyQt App, and Expose VNC

on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check ngrok Installation
      run: ngrok version

    - name: Install Dependencies (e.g., Python, PyQt, ngrok)
      run: |
        brew install python
        python3 -m venv venv
        source venv/bin/activate
        brew install ngrok

    - name: Set VNC Password
      run: |
        echo "123456" > ~/.vncpass
        chmod 600 ~/.vncpass

    - name: Start macOS Screen Sharing (VNC Server)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users $USER -privs -all -clientopts -setvnclegacy -vnclegacy yes
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

    - name: Start ngrok (expose VNC port)
      run: |
        ngrok tcp 5900 --log=stdout > ngrok.log 2>&1 &
        sleep 15
        cat ngrok.log
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Fetch ngrok Public URL
      run: |
        for i in {1..10}; do
          RESPONSE=$(curl -s http://127.0.0.1:4040/api/tunnels | python3 -c "import sys, json; data = sys.stdin.read(); print(json.loads(data)['tunnels'][0]['public_url'])" 2>/dev/null || echo "")
          if [ -n "$RESPONSE" ]; then
            echo "ngrok URL: $RESPONSE"
            break
          fi
          echo "Retrying..."
          sleep 3
        done